site_name: HADes
site_url: https://patarimi.github.io/hades
watch:
  - hades

nav:
  - Home: README.md
  - CLI-Command: CLI-ref.md
  - API-Reference: reference/

theme:
  name: material
markdown_extensions:
  - mkdocs-typer
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx