[tool.poetry]
name = "hades"
version = "0.1.0"
description = ""
authors = ["Patarimi <38954040+Patarimi@users.noreply.github.com>"]
readme = "docs/README.md"

[tool.poetry.scripts]
hades = "hades.main:app"

[tool.poe.tasks]
update = "poetry show -l -o"
publish     = "poetry publish --build --username __token__ --password $PYPI_TOKEN"
doc         = "mkdocs gh-deploy"

[tool.poetry.dependencies]
python = "^3.10,<3.13"
typer = "^0.9.0"
gdstk = "^0.9.42"
setuptools = "^68.0.0"
pyyaml = "^6.0"
scipy = "^1.11.1"
python-dotenv = "^1.0.0"
volare = "^0.9.0"
rich = "^12.0"
scikit-rf = "^0.28.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
poethepoet = "^0.21.0"
pytest = "^7.4.0"
pytest-sugar = "^0.9.7"


[tool.poetry.group.doc.dependencies]
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.18"
mkdocs-typer = "^0.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
