start: (layer)+

layer: NAME _SEP (SETOFTYPE | TYPE) _SEP INTEGER _SEP INTEGER _SEP? _NL?
    | "NAME" _SEP NAME "/" TYPE ("," NAME "/" TYPE)* _SEP INTEGER _SEP INTEGER _SEP? _NL?

INTEGER: /[0-9]+/
SETOFTYPE: (TYPE ",")* TYPE
TYPE: WORD
NAME: WORD
_SEP: (" "|/\t/)+
WORD: LETTER (LETTER|"0".."9"|"_")*
COMMENT: "#" /.+/ _NL
%ignore COMMENT
%ignore "cut"
%import common.LETTER
%import common.NEWLINE -> _NL